In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
data=pd.read_csv("data_new.csv")
type(data)



pandas.core.frame.DataFrame

In [5]:
data

ge   cst         ms     fmi       fs        fo         mo       nf  \
0    F     G  Unmarried  Medium  Average    Farmer  Housewife    Large   
1    M   OBC  Unmarried     Low  Average   Service    Service    Small   
2    F   OBC  Unmarried      Am  Average   Service  Housewife  Average   
3    M  MOBC  Unmarried  Medium    Small  Business   Business    Large   
4    M     G  Unmarried      Am  Average   Service  Housewife    Large   
5    M   OBC  Unmarried  Medium  Average    Farmer  Housewife    Small   
6    F   OBC  Unmarried    High  Average   Service    Service  Average   
7    F   OBC  Unmarried  Medium    Small    Farmer  Housewife    Small   
8    F  MOBC  Unmarried     Low    Small    Others  Housewife    Small   
9    F   OBC  Unmarried     Low    Small    Others  Housewife    Large   
10   M    ST  Unmarried      Vh    Small   Retired    Retired    Large   
11   F   OBC  Unmarried  Medium  Average   Service  Housewife    Large   
12   M   OBC  Unmarried  Medium    Small   Service  Housewife    Large   
13   M   OBC  Unmarried  Medium    Small    Others  Housewife    Large   
14   F     G  Unmarried  Medium    Small  Business  Housewife    Large   
15   F    ST  Unmarried  Medium    Small    Others  Housewife    Large   
16   F    ST  Unmarried  Medium    Small  Business  Housewife    Large   
17   M   OBC  Unmarried     Low    Small    Farmer  Housewife    Large   
18   M    ST  Unmarried  Medium  Average    Farmer  Housewife    Large   
19   M    ST  Unmarried  Medium    Small    Farmer  Housewife    Large   
20   F     G  Unmarried      Vh    Small   Service  Housewife    Large   
21   F     G  Unmarried      Vh    Small   Service  Housewife    Large   
22   F   OBC  Unmarried      Am    Small  Business    Service    Large   
23   F   OBC  Unmarried  Medium    Small    Farmer  Housewife    Large   
24   F     G  Unmarried  Medium  Average  Business  Housewife    Large   
25   F     G  Unmarried  Medium  Average  Business  Housewife    Large   
26   F   OBC  Unmarried  Medium    Small   Service  Housewife    Large   
27   F   OBC  Unmarried  Medium  Average    Others  Housewife    Large   
28   M     G  Unmarried    High  Average   Service  Housewife    Large   
29   F   OBC  Unmarried      Am  Average    Others  Housewife    Small   
..  ..   ...        ...     ...      ...       ...        ...      ...   
101  M  MOBC  Unmarried  Medium  Average    Farmer    Service    Small   
102  M     G  Unmarried  Medium    Small    Farmer  Housewife  Average   
103  M     G  Unmarried  Medium    Small    Farmer  Housewife  Average   
104  M   OBC  Unmarried     Low    Small   Service    Service    Large   
105  M     G  Unmarried  Medium    Small   Service  Housewife  Average   
106  M  MOBC  Unmarried  Medium    Small   Service  Housewife    Large   
107  M   OBC  Unmarried  Medium    Small    Others    Service  Average   
108  F   OBC  Unmarried    High    Small   Service    Service  Average   
109  M   OBC  Unmarried  Medium  Average    Farmer  Housewife  Average   
110  M    ST  Unmarried  Medium    Small    Farmer  Housewife  Average   
111  M    ST  Unmarried     Low    Small    Farmer  Housewife    Small   
112  M    ST  Unmarried  Medium    Small   Retired  Housewife  Average   
113  F     G  Unmarried  Medium    Small  Business  Housewife  Average   
114  F     G  Unmarried     Low    Small    Others  Housewife  Average   
115  F     G  Unmarried  Medium  Average  Business  Housewife  Average   
116  M     G  Unmarried     Low    Small    Farmer  Housewife  Average   
117  M     G  Unmarried    High    Small    Others  Housewife  Average   
118  M   OBC  Unmarried  Medium    Small    Others  Housewife  Average   
119  M     G  Unmarried      Am    Small   Service  Housewife  Average   
120  F     G  Unmarried  Medium    Small    Farmer  Housewife    Small   
121  M   OBC  Unmarried  Medium  Average    Farmer  Housewife  Average   
122  M   OBC  Unmarried  Medium  Average   Service  Housewife  Average   
123  M  

In [2]:
from sklearn.preprocessing import LabelEncoder
processed_data=pd.DataFrame()
lb_make = LabelEncoder()
processed_data["ge"] = lb_make.fit_transform(data["ge"])
processed_data["cst"] = lb_make.fit_transform(data["cst"])
processed_data["ms"] = lb_make.fit_transform(data["ms"])
processed_data["fmi"] = lb_make.fit_transform(data["fmi"])
processed_data["fs"] = lb_make.fit_transform(data["fs"])
processed_data["fo"] = lb_make.fit_transform(data["fo"])
processed_data["mo"] = lb_make.fit_transform(data["mo"])
processed_data["nf"] = lb_make.fit_transform(data["nf"])
processed_data["sh"] = lb_make.fit_transform(data["sh"])
processed_data["ss"] = lb_make.fit_transform(data["ss"])
processed_data["me"] = lb_make.fit_transform(data["me"])

In [7]:
processed_data

ge  cst  ms  fmi  fs  fo  mo  nf  sh  ss  me
0     0    0   0    3   0   1   1   1   2   0   0
1     1    2   0    2   0   4   4   2   2   0   0
2     0    2   0    0   0   4   1   0   0   0   0
3     1    1   0    3   2   0   0   1   2   0   0
4     1    0   0    0   0   4   1   1   2   1   0
5     1    2   0    3   0   1   1   2   2   1   2
6     0    2   0    1   0   4   4   0   2   0   0
7     0    2   0    3   2   1   1   2   2   1   0
8     0    1   0    2   2   2   1   2   1   0   0
9     0    2   0    2   2   2   1   1   0   0   0
10    1    4   0    4   2   3   3   1   1   1   2
11    0    2   0    3   0   4   1   1   0   0   2
12    1    2   0    3   2   4   1   1   2   1   2
13    1    2   0    3   2   2   1   1   1   0   0
14    0    0   0    3   2   0   1   1   2   0   2
15    0    4   0    3   2   2   1   1   0   0   0
16    0    4   0    3   2   0   1   1   2   1   2
17    1    2   0    2   2   1   1   1   0   0   2
18    1    4   0    3   0   1   1   1   0   0   2
19    1    4   0    3   2   1   1   1   2   0   2
20    0    0   0    4   2   4   1   1   2   0   2
21    0    0   0    4   2   4   1   1   2   1   2
22    0    2   0    0   2   0   4   1   0   0   2
23    0    2   0    3   2   1   1   1   0   0   2
24    0    0   0    3   0   0   1   1   2   0   2
25    0    0   0    3   0   0   1   1   2   0   2
26    0    2   0    3   2   4   1   1   2   0   2
27    0    2   0    3   0   2   1   1   0   1   2
28    1    0   0    1   0   4   1   1   2   1   2
29    0    2   0    0   0   2   1   2   0   1   0
..   ..  ...  ..  ...  ..  ..  ..  ..  ..  ..  ..
101   1    1   0    3   0   1   4   2   0   0   0
102   1    0   0    3   2   1   1   0   0   0   0
103   1    0   0    3   2   1   1   0   0   0   0
104   1    2   0    2   2   4   4   1   0   0   0
105   1    0   0    3   2   4   1   0   0   0   0
106   1    1   0    3   2   4   1   1   0   1   0
107   1    2   0    3   2   2   4   0   2   0   0
108   0    2   0    1   2   4   4   0   0   0   0
109   1    2   0    3   0   1   1   0   0   0   0
110   1    4   0    3   2   1   1   0   0   0   0
111   1    4   0    2   2   1   1   2   2   0   0
112   1    4   0    3   2   3   1   0   0   0   0
113   0    0   0    3   2   0   1   0   0   1   0
114   0    0   0    2   2   2   1   0   2   0   0
115   0    0   0    3   0   0   1   0   1   0   0
116   1    0   0    2   2   1   1   0   0   0   0
117   1    0   0    1   2   2   1   0   0   0   0
118   1    2   0    3   2   2   1   0   0   1   0
119   1    0   0    0   2   4   1   0   0   0   0
120   0    0   0    3   2   1   1   2   2   0   0
121   1    2   0    3   0   1   1   0   0   0   0
122   1    2   0    3   0   4   1   0   2   0   0
123   1    2   0    0   0   0   1   0   1   0   2
124   1    2   0    3   0   4   1   0   0   0   0
125   1    2   0    3   0   4   1   2   0   0   2
126   1    0   0    2   2   4   1   2   0   0   0
127   1    1   0    1   2   1   1   0   2   0   0
128   0    2   0    0   1   1   1   2   0   0   0
129   1    4   0    2   0   4   1   0   0   0   0
130   1    0   0    3   2   0   1   0   0   0   0

[131 rows x 11 columns]

In [5]:
features=processed_data.columns
print(features)

Index([u'ge', u'cst', u'ms', u'fmi', u'fs', u'fo', u'mo', u'nf', u'sh', u'ss',
       u'me'],
      dtype='object')


In [6]:
features_raw=processed_data.columns[-1]
features_raw


'me'

In [7]:
predict_class=data.columns[-1]
predictions=data[predict_class]
predictions

0         Good
1      Average
2         Good
3      Average
4         Good
5      Average
6         Good
7         Good
8         Good
9         Good
10        Good
11        Good
12        Good
13        Good
14        Good
15        Good
16        Good
17        Good
18        Good
19        Good
20        Good
21        Good
22        Good
23        Good
24        Good
25     Average
26     Average
27        Good
28     Average
29     Average
        ...   
101    Average
102       Good
103    Average
104       Poor
105       Poor
106    Average
107       Poor
108       Poor
109    Average
110       Poor
111       Poor
112       Poor
113       Good
114    Average
115    Average
116       Poor
117    Average
118    Average
119    Average
120       Good
121       Poor
122       Poor
123    Average
124       Poor
125       Good
126       Poor
127    Average
128       Good
129    Average
130    Average
Name: atd, Length: 131, dtype: object

In [8]:
predict_class = predictions.apply(lambda x: 0 if (x == "Poor") else(1 if x =="Average" else 2))
predict_class

0      2
1      1
2      2
3      1
4      2
5      1
6      2
7      2
8      2
9      2
10     2
11     2
12     2
13     2
14     2
15     2
16     2
17     2
18     2
19     2
20     2
21     2
22     2
23     2
24     2
25     1
26     1
27     2
28     1
29     1
      ..
101    1
102    2
103    1
104    0
105    0
106    1
107    0
108    0
109    1
110    0
111    0
112    0
113    2
114    1
115    1
116    0
117    1
118    1
119    1
120    2
121    0
122    0
123    1
124    0
125    2
126    0
127    1
128    2
129    1
130    1
Name: atd, Length: 131, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split

np.random.seed(1234)

X_train, X_test, y_train, y_test = train_test_split(processed_data, predict_class, train_size=0.80, random_state=1)


# Show the results of the split
print "Training set has {} samples.".format(X_train.shape[0])
print "Testing set has {} samples.".format(X_test.shape[0])

Training set has 104 samples.
Testing set has 27 samples.


/home/joju/opencv/local/lib/python2.7/site-packages/sklearn/model_selection/_split.py:2069: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [26]:
#SVM Classifier

import sklearn
from sklearn import svm

from sklearn.model_selection import cross_val_score

C = 1.0
svc = svm.SVC(kernel='linear',C=C,gamma=2)
svc.fit(X_train, y_train)

from sklearn.metrics import fbeta_score
predictions_test = svc.predict(X_test)
print(predictions_test)

from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix  
# Model Accuracy: how often is the classifier correct?
print(confusion_matrix(y_test,predictions_test))



[2 1 2 2 1 0 1 0 2 1 2 1 2 2 2 2 2 1 1 1 0 1 2 2 2 2 1]
[[2 2 4]
 [1 3 4]
 [0 5 6]]


"\n\nfrom sklearn import metrics\nfrom sklearn.metrics import classification_report, confusion_matrix\n\nprint(confusion_matrix(y_test, predictions_test))\nprint(classification_report(y_test, predictions_test))\n\nplt.subplot(221), plt.hist(predictions_test, bins=10)\nplt.xlim(0,1)\nplt.xlabel('prediction test')\nplt.ylabel('Frequency')\n"

In [27]:
print(classification_report(y_test,predictions_test))

              precision    recall  f1-score   support

           0       0.67      0.25      0.36         8
           1       0.30      0.38      0.33         8
           2       0.43      0.55      0.48        11

   micro avg       0.41      0.41      0.41        27
   macro avg       0.47      0.39      0.39        27
weighted avg       0.46      0.41      0.40        27



In [28]:
print('Accuracy is',metrics.accuracy_score(y_test,predictions_test))

('Accuracy is', 0.4074074074074074)


In [30]:
input_data = pd.DataFrame([[1,0,0,3,2,0,1,0,0,0,0]])
input_data

predictions_test = svc.predict(input_data)
print(predictions_test)


[1]
